name = "CheckedSizeProduct"
uuid = "1b2cc9da-92e3-4b71-9788-30fc110eefda"
authors = ["Neven Sajko <s@purelymail.com> and contributors"]
version = "1.0.0"

[compat]
julia = "1"
Aqua = "0.8"
Test = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
